"""empty message

Revision ID: e0ba1f6aa238
Revises: 9db61aec2b69
Create Date: 2023-04-26 20:05:06.621165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0ba1f6aa238'
down_revision = '9db61aec2b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('times', schema=None) as batch_op:
        batch_op.drop_constraint('times_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'times', ['time_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('time_id')

    with op.batch_alter_table('times', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('times_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
